### ISSUE TITLE
lionfish +/- SD is misleading 

### ISSUE THREAD

**Issue by mhepner90** [marinebon/info-fk#11]
There is no LF prior to 2009, but the way the SD is calculated it is reducing the mean +/- SD

**Comment by 7yl4r** [comment]
This is a problem with [the data csv](https://raw.githubusercontent.com/marinebon/info-fk/master/prep/data/rvc_trophic_groups/lionfish_bio.csv) itself, which does have 0 values for the `biomass_mean` columns. I think we want these to be NA (or drop the row).
