### ISSUE TITLE
x axis ticks 

### ISSUE THREAD

**Issue by mhepner90** [marinebon/info-fk#9]
Add more ticks to x-axis

e.g. Years display every 4 years with tick marks on every two. (2000, 2004, 2008, 2012, etc.)

**Comment by 7yl4r** [comment]
might be trickier than it seems: https://github.com/marinebon/infographiq/issues/8

Do you think if we make the `valueRange` a longer list we might get lucky? We could add some dates in between today and the start of the data.

```R
    dyAxis('x', label=x_label, valueRange=c(as.Date(min(d$t)), today())) %>%
```

**Comment by 7yl4r** [comment]
dup of https://github.com/marinebon/infographiq/issues/8
